# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: C_OCR.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x43_OCR.proto\"0\n\x07Request\x12\x11\n\tImageType\x18\x01 \x01(\t\x12\x12\n\nImageBytes\x18\x02 \x01(\x0c\",\n\x08Response\x12\x0c\n\x04Text\x18\x01 \x01(\t\x12\x12\n\nImageBytes\x18\x02 \x01(\x0c\x32%\n\x05\x43_OCR\x12\x1c\n\x03Ocr\x12\x08.Request\x1a\t.Response\"\x00\x62\x06proto3')



_REQUEST = DESCRIPTOR.message_types_by_name['Request']
_RESPONSE = DESCRIPTOR.message_types_by_name['Response']
Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'C_OCR_pb2'
  # @@protoc_insertion_point(class_scope:Request)
  })
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'C_OCR_pb2'
  # @@protoc_insertion_point(class_scope:Response)
  })
_sym_db.RegisterMessage(Response)

_C_OCR = DESCRIPTOR.services_by_name['C_OCR']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST._serialized_start=15
  _REQUEST._serialized_end=63
  _RESPONSE._serialized_start=65
  _RESPONSE._serialized_end=109
  _C_OCR._serialized_start=111
  _C_OCR._serialized_end=148
# @@protoc_insertion_point(module_scope)
