# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import C_OCR_pb2 as C__OCR__pb2


class C_OCRStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ocr = channel.unary_unary(
                '/C_OCR/Ocr',
                request_serializer=C__OCR__pb2.Request.SerializeToString,
                response_deserializer=C__OCR__pb2.Response.FromString,
                )


class C_OCRServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Ocr(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_C_OCRServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ocr': grpc.unary_unary_rpc_method_handler(
                    servicer.Ocr,
                    request_deserializer=C__OCR__pb2.Request.FromString,
                    response_serializer=C__OCR__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'C_OCR', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class C_OCR(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Ocr(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/C_OCR/Ocr',
            C__OCR__pb2.Request.SerializeToString,
            C__OCR__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
